/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import domain.Car;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose0
 */
public class ViewAllVehicles extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    List<Car> vehiclesList;
    Object[] fila;

    /**
     * Creates new form viewAllVehicles
     *
     * @param <error>
     */
    public ViewAllVehicles() {
    }

    public ViewAllVehicles(List<Car> vehicles) {
        initComponents();
        this.setBackground(Color.lightGray);
        model.addColumn("Nombre");
        model.addColumn("Marca");
        model.addColumn("Placa");
        model.addColumn("Año");
        model.addColumn("Km");
        model.addColumn("Color");
        model.addColumn("Americano");
        model.addColumn("Serie");
        vehiclesTable.setModel(model);
        vehiclesList = vehicles;
        addVehiclesTable();
    }

    public void addVehiclesTable() {
        model.setRowCount(0);
        for (Car vehicle : vehiclesList) {//Recorro los Clientes
            if (vehicle.getSeries() > 0 ) {
                fila = new Object[]{
                    
                    vehicle.getName(),
                    vehicle.getBrand(),
                    vehicle.getLicensePlate(),
                    vehicle.getModel(),
                    vehicle.getMileage(),
                    vehicle.getColor(),
                    vehicle.isAmerican(),
                    vehicle.getSeries()
                    
                    
                        

                };
                model.addRow(fila);//agrega el cliente a la tabla
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vehiclesTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Año", "Kilometros", "Americano", "Serie"
            }
        ));
        jScrollPane1.setViewportView(vehiclesTable);

        closeButton.setText("Cerrar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vehiclesTable;
    // End of variables declaration//GEN-END:variables
}
